." Manpage for titania.
." Contact holger.seelig@yahoo.de to correct errors or typos.
.TH man 1 "19 January 2017" "Version 2.0" "x3dtidy man page"
.SH NAME

        titania - Titania X3D Browser

.SH SYNOPSIS

        titania [OPTIONS] [FILE]

.SH DESCRIPTION

        Titania is a X3D/VRML editor and browser for Ubuntu. The goal is
        a full standard compliant X3D browser for future releases of Ubuntu.
        For now, Titania fully supports the Moving Worlds specification for
        VRML 2.0 and already many parts of the X3D specification.

        It can be used as a simple 3D viewer for .x3d files, as high quality
        3D animation rendering engine, for advanced science simulations,
        live data visualization, or as easy to use gaming engine.

        Furthermore Titania can be used as converter and beautifier for
        various file formats from the command line. It can format or convert
        a file to standard output or to your hard disk.

        Titania reads an X3D file and writes an indented, reformatted file.
        When no output file is specified the output is printed to stdout.
        Use the --style option to specify the desired output style.

.SH OPTIONS

General Options

        -h, --help
               prints usage

Export Options

        -i FILENAME, --input=FILENAME
               input filename

        -e FILENAME, --export=FILENAME
               export filename

        -s MODE, --style=MODE
               MODE can be 'smallest', 'small ', 'compact', or 'nicest'
               nicest is the default mode

List Options

        -l LIST, --list=profiles|components|nodes|fields
               Get a list of all supported profiles, components, nodes or fields.

.SH KNOWN EXPORT FILE FORMATS

Accepted input file formats are:

        .x3d         X3D XML Encoding
        .x3dz        X3D XML Encoding
        .x3dv        X3D Classic VRML Encoding
        .x3dvz       X3D Classic VRML Encoding"
        .json        X3D JSON Encoding
        .wrl         VRML Encoding
        .wrz         VRML Encoding
        .obj         Alias Wavefront OBJ File Format
        .3ds         Autodesk 3DS File Format
        .pdf         Portable Document Format (optional)
        .svg         Scalable Vector Grafics
        .svgz        Scalable Vector Grafics

        PDF file format is optional and is available if Inkscape is installed. 

Accepted output file formats are:

        .x3d         X3D XML Encoding
        .x3dv        X3D Classic VRML Encoding
        .json        X3D JSON Encoding

.SH EXAMPLES

General Examples

        titania scene.x3d
                Open scene.x3d in browser.

Export Examples

        titania --style=compact --input=input.x3d --export=-
                Formats input.x3d's contents in compact style mode to
                standard output.

        titania --input=input.x3dv --export=beautified.x3dv
                Formats input.x3dv's contents and saves the output in
                beautified.x3dv.

        titania --input=input.3ds --export=output.json
                Converts input.3ds's contents and saves the output in
                output.json.

.SH COPYRIGHT

        Copyright © 2010 Holger Seelig.  License GPLv3+:
        GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
        This is free software: you are free to change and redistribute it.
        There is NO WARRANTY, to the extent permitted by law.
