name: titania
version-script: perl -wln -e 'print $1 if /version\s*=\s*"(.*?)"/' ../libtitania-x3d/Titania/X3D/Browser/X3DBrowser.cpp
version: devel
summary: Titania is a X3D/VRML editor and browser for the Linux Platform.
description: |
  Titania is a X3D/VRML editor and browser for the Linux Platform. It is fully
  standard compliant. Titania fully supports the Moving Worlds specification for
  VRML 2.0 and the X3D specification.

  Whether you are a graphic designer, modeller, or scientist, Titania provides
  you with sophisticated tools to get your job done. It supports the entirety
  of the X3D pipeline — modeling, rigging, animation, simulation, rendering,
  and compositing.

  Tiania requires to run a NVIDIA or ATI graphics card, at least 1024 MB RAM,
  and a monitor resolution of at least 1280 × 1024 pixels.
icon: titania.svg

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
 # - build-on: i386

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

slots:
  dbus-titania:
    interface: dbus
    bus: session
    name: de.create3000.titania

apps:
  titania:
    command: bin/desktop-launch $SNAP/bin/titania-launch $SNAP/bin/titania
    desktop: share/applications/de.create3000.titania.desktop
    adapter: none
    slots:
      - dbus-titania
    plugs:
      - alsa
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - opengl
      - pulseaudio
      - removable-media
      - unity7
      - wayland
      - x11

parts:
  desktop-gtk3:
    source: https://github.com/Ubuntu/snapcraft-desktop-helpers.git
    source-type: git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
  desktop-titania:
    plugin: dump
    source: files/
    override-build: |
      set -eux
      snapcraftctl build
      chmod +x bin/titania-launch
  titania:
    plugin: autotools
    source: https://github.com/create3000/titania
    source-type: git
    after:
      - desktop-gtk3
      - desktop-titania
    configflags:
      - --enable-debug
    build-packages:
      - intltool
      - libbullet-dev
      - libcgal-dev
      - libcurl4-gnutls-dev
      - libfontconfig1-dev
      - libgl1-mesa-dev
      - libglew-dev
      - libglu1-mesa-dev
      - libgmp-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libgstreamermm-1.0-dev
      - libgtkmm-3.0-dev
      - libgtksourceviewmm-3.0-dev
      - libgtop2-dev
      - libjson-c-dev
      - libmozjs-60-dev
      - libmpfr-dev
      - libsqlite3-dev
      - libtool
      - libtool-bin
      - libxml++2.6-dev
      - mesa-common-dev
      - zlib1g-dev
    stage-packages:
      - ffmpeg
      - gettext
      - gstreamer1.0-alsa
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-x
      - libbullet2.87
      - libcgal13
      - libcurl4
      - libfontconfig1
      - libgl1-mesa-glx
      - libglew2.1
      - libglu1-mesa
      - libgmp10
      - libgstreamermm-1.0-1
      - libgtkmm-3.0-1v5
      - libgtksourceviewmm-3.0-0v5
      - libgtop-2.0-11
      - libjson-c3
      - libmozjs-60-0
      - libmpfr6
      - libsqlite3-0
      - libx264-155
      - libxml++2.6-2v5
      - libxvidcore4
      - zlib1g
      - libstdc++6 # extra
      - libc6
      - libc-bin
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - fcitx-frontend-gtk3
    override-build: |
      set -eux
      snapcraftctl build
      glib-compile-schemas $SNAPCRAFT_PART_INSTALL/usr/share/glib-2.0/schemas
      update-mime-database $SNAPCRAFT_PART_INSTALL/usr/share/mime
      update-mime-database $SNAPCRAFT_PART_INSTALL/share/mime
