name: titania
version-script: perl -wln -e 'print $1 if /version\s*=\s*"(.*?)"/' ../libtitania-x3d/Titania/X3D/Browser/X3DBrowser.cpp
version: devel
summary: Titania is a X3D/VRML editor and browser for the Linux Platform.
description: |
  Whether you are a graphic designer, modeller, or scientist, Titania provides
  you with sophisticated tools to get your job done. It supports the entirety
  of the X3D pipeline — modeling, rigging, animation, simulation, rendering,
  and compositing.
icon: titania.svg

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
 # - build-on: i386

apps:
  titania:
    command: desktop-launch $SNAP/bin/titania
    desktop: share/applications/de.create3000.titania.desktop
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/share:$SNAP/usr/share:$XDG_DATA_DIRS
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri:$LIBGL_DRIVERS_PATH
#      LANG: C
#      LC_ALL: C
    plugs:
      - alsa
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - opengl
      - pulseaudio
      - removable-media
      - unity7
      - wayland
      - x11

parts:
  desktop-gtk3:
    source: https://github.com/Ubuntu/snapcraft-desktop-helpers.git
    source-type: git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - adwaita-icon-theme
      - dmz-cursor-theme
      - gnome-themes-standard
      - libappindicator3-1
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-0
      - libgtk-3-bin
      - libxkbcommon0
      - light-themes
      - locales
      - locales-all
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - mesa-vulkan-drivers
      - shared-mime-info
      - ttf-ubuntu-font-family
      - unity-gtk3-module
      - xdg-user-dirs
  titania:
    plugin: autotools
    source: https://github.com/create3000/titania
    source-type: git
    after:
      - desktop-gtk3
    build-packages:
      - gettext
      - intltool
      - libbullet-dev
      - libcgal-dev
      - libcurl4-gnutls-dev
      - libfontconfig1-dev
      - libgl1-mesa-dev
      - libglew-dev
      - libglu1-mesa-dev
      - libgmp-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libgstreamermm-1.0-dev
      - libgtkmm-3.0-dev
      - libgtksourceviewmm-3.0-dev
      - libgtop2-dev
      - libjson-c-dev
      - libmagick++-dev
      - libmozjs-60-dev
      - libmpfr-dev
      - libsqlite3-dev
      - libtool
      - libtool-bin
      - libxml++2.6-dev
      - mesa-common-dev
      - zlib1g-dev
    stage-packages:
      - ffmpeg
      - gettext
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
      - libbullet2.87
      - libc-bin
      - libc6
      - libcgal13
      - libcurl4
      - libfontconfig1
      - libgl1-mesa-glx
      - libglew2.1
      - libglu1-mesa
      - libgmp10
      - libgstreamermm-1.0-1
      - libgtkmm-3.0-1v5
      - libgtksourceviewmm-3.0-0v5
      - libgtop-2.0-11
      - libjson-c3
      - libmagick++-6.q16-8
      - libmozjs-60-0
      - libmpfr6
      - libsqlite3-0
      - libx264-155
      - libxml++2.6-2v5
      - libxvidcore4
      - ttf-ubuntu-font-family
      - zlib1g
